on:
  push:
    branches:
      - dev

name: Configure environemnt for deployment

jobs:
  config:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/variable-substitution@v1 
        with:
          files: 'app.yaml'
        env:
          NAMESPACE: ${{ secrets.NAMESPACE }}